application:
  security:
    jwt:
      secret-key: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/auth_jwt?createDatabaseIfNotExist=true
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: RESTAURANT-AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    hostname: eureka-server

server:
  port: 8081
  servlet:
    context-path: /auth

